services:
  fast_granja_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "5432:5432"

  fast_granja_app:
    image: fast_granja_app
    build: .
    entrypoint: ["sh", "./entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - "fast_granja_database"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}

volumes:
  pgdata: