"""adicionando Flock

Revision ID: 1f9ffaa08a85
Revises: 3107c97a2f0a
Create Date: 2025-06-29 03:43:35.829064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f9ffaa08a85"
down_revision: Union[str, Sequence[str], None] = "3107c97a2f0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("arrival_date", sa.Date(), nullable=False),
        sa.Column("supplier_name", sa.String(), nullable=False),
        sa.Column("flock_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flock_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flock")
    # ### end Alembic commands ###
