"""criação tabela chicken_death

Revision ID: 3523c365e965
Revises: 9fd26cadda62
Create Date: 2025-07-12 03:30:24.669851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3523c365e965"
down_revision: Union[str, Sequence[str], None] = "9fd26cadda62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chicken_death",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("flock_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["flock_id"], ["flock.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chicken_death")
    # ### end Alembic commands ###
