"""trocando isActive por isactive

Revision ID: 8ac9113dad9b
Revises: c8c1fe71756f
Create Date: 2025-07-21 12:05:55.234297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ac9113dad9b"
down_revision: Union[str, Sequence[str], None] = "c8c1fe71756f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flock", sa.Column("isactive", sa.Boolean(), nullable=False))
    op.drop_column("flock", "isActive")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flock",
        sa.Column("isActive", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("flock", "isactive")
    # ### end Alembic commands ###
