"""criação tabelas de tipos e adicão do relaçionamentos entre as tabelas de flock e chicken_death com seus respectivos tipos

Revision ID: 99cbdfa43053
Revises: 3523c365e965
Create Date: 2025-07-12 03:49:58.945725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99cbdfa43053"
down_revision: Union[str, Sequence[str], None] = "3523c365e965"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chicken_death_reason",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chicken_race",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("chicken_death", sa.Column("reason_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None,
        "chicken_death",
        "chicken_death_reason",
        ["reason_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("chicken_death", "reason")
    op.add_column("flock", sa.Column("race_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "flock", "chicken_race", ["race_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_column("flock", "race")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flock", sa.Column("race", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "flock", type_="foreignkey")
    op.drop_column("flock", "race_id")
    op.add_column(
        "chicken_death",
        sa.Column("reason", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "chicken_death", type_="foreignkey")
    op.drop_column("chicken_death", "reason_id")
    op.drop_table("chicken_race")
    op.drop_table("chicken_death_reason")
    # ### end Alembic commands ###
