"""tabela DailyEggsModel + relação com flock

Revision ID: 9fd26cadda62
Revises: fbfe652544ba
Create Date: 2025-07-03 04:11:45.048677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fd26cadda62"
down_revision: Union[str, Sequence[str], None] = "fbfe652544ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_eggs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total_eggs", sa.Integer(), nullable=False),
        sa.Column("broken_eggs", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("flock_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["flock_id"], ["flock.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_eggs")
    # ### end Alembic commands ###
