"""adicionando campo price em flock

Revision ID: c615020ec165
Revises: 1f9ffaa08a85
Create Date: 2025-06-29 04:58:48.576150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c615020ec165"
down_revision: Union[str, Sequence[str], None] = "1f9ffaa08a85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flock", sa.Column("price", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flock", "price")
    # ### end Alembic commands ###
