"""adição de unique em chickendeathreason e chickenrace

Revision ID: c8c1fe71756f
Revises: 99cbdfa43053
Create Date: 2025-07-14 03:27:09.548500

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c8c1fe71756f"
down_revision: Union[str, Sequence[str], None] = "99cbdfa43053"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "chicken_death_reason", ["reason"])
    op.create_unique_constraint(None, "chicken_race", ["race"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chicken_race", type_="unique")
    op.drop_constraint(None, "chicken_death_reason", type_="unique")
    # ### end Alembic commands ###
